name: Heroku Deploy Api

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8     
    - run: mvn -B package --file pom.xml
  deploy-webapp:
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "back-wiki-g03" #Must be unique in Heroku
          heroku_email: "jelabra@gmail.com"
          usedocker: true
          docker_build_args: |
            API_URI
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
